### ISSUE TITLE
Integrating with Ionic 3 is not working

### ISSUE THREAD

**Issue by premjo** [techaffinity/freshchat-phonegap#11]
I wanted to integrate the freshchat for ionic app.

I have initiated the FreshChat as below mention.
window.Freshchat.init({
   appId       : "<Your App Id>",
   appKey      : "<Your App Key>",
   gallerySelectionEnabled   : true,
   cameraCaptureEnabled      : true,
   teamMemberInfoVisible     : true
});
I'm trying to pop out the conversation channel.  But its not working..
  window.Freshchat.showConversations();

Is that plugin will support for IONIC framework ?

Please let me know, if i have missed any configuration stuff.

**Comment by alan-grixti** [comment]
Hi, I have used this on Ionic 3 yesterday and it worked out correctly. Same config as you, but called within the platform.deviceReady() callback

**Comment by premjo** [comment]
Yeah! i'm calling the function within platform.deviceReady callback only app.component.ts. 
When i'm trying to call the function showConversation. Its throwing error saying "please invoke the init method first before call the showConversation method".
So i'have called the init method once again from inside the constructor of page but i'm still getting the below error.
Error: Uncaught (in promise): TypeError: Cannot read property 'init' of undefined TypeError: Cannot read property 'init' of undefined.

**Comment by alan-grixti** [comment]
Browser does not support the plugin. I'm only getting that message within the browser. Is that the case?
I've _if conditioned_ myself out of it.

**Comment by premjo** [comment]
Yeah i have done the same. Since it wont work in browser. But mobile app is not responding as expected to debug i have added the device to chrome://inspect (USB Enable Debugging). 
If i check through mobile i'm not getting any response. 
Can you please add the screen if you call method showConversation or showFAQs method any of page. Just to know what would be response.

**Comment by premjo** [comment]
Hi @alan-grixti @techaffinity ,
Any updates on this issue.

**Comment by techaffinity** [comment]
You can access Freshchat object like this 
(window as any).Freshchat.init({ appId : "", appKey : "" }); });

Please refer readme for ionic .

**Comment by techaffinity** [comment]
First call (window as any).Freshchat.init({ appId : "", appKey : "" }); });
After the successfuly initialized .Then
 you call method showConversation or showFAQs.

**Comment by wishbooks** [comment]
i followed the steps here https://github.com/techaffinity/freshchat-phonegap
used this to resolve the issue still same error my code https://codeshare.io/5ovJ9b
<img width="1280" alt="screen shot 2018-07-05 at 5 03 26 pm" src="https://user-images.githubusercontent.com/17745163/42326739-a54ba39c-8087-11e8-9755-db73f980348b.png">

`function showFreshChat()
{
  console.log("freshchat");
  var profile = JSON.parse(localStorage.getItem('profile'));
  console.log(profile);

  if(wGlobal.platform == '')
  {
      window.fcWidget.init({
        
              token      : "4d1f51cc-687c-4e81-9ec9-e3d0105ede1d",
              host       : "https://wchat.freshchat.com",
              externalId : profile.username,     // user’s id unique to your system
              firstName  : profile.first_name,   // user’s first name
              lastName   : profile.last_name,    // user’s last name
              email      : profile.email,    // user’s email address
              phone      : profile.userprofile.phone_number,  // phone number without country code
              phoneCountryCode: "+91",
              restoreId  : localStorage.getItem('freshchatrestotreId'+profile.username),
              config     : { 
                                headerProperty:
                                {
                                  //Set Widget to be left to right.
                                  direction: 'ltr'
                                }
                            }
            });

          window.fcWidget.user.get(function(resp)
          {
            var status = resp && resp.status,
                data = resp && resp.data;
            if (status !== 200)
            {
              window.fcWidget.user.setProperties({
                firstName  : profile.first_name,   // user’s first name
                lastName   : profile.last_name,    // user’s last name
                email      : profile.email,    // user’s email address
                phone      : profile.userprofile.phone_number, // phone number without country code
                phoneCountryCode: "+91",
                plan       : "Estate",                 // user's meta property 1
                status     : "Active",               // user's meta property 2
              });
              window.fcWidget.on('user:created', function(resp)
              {
                var status = resp && resp.status,
                    data = resp && resp.data;

                if (status === 200) {
                  if (data.restoreId)
                  {
                    localStorage.setItem("freshchatrestotreId"+profile.username, data.restoreId);// Update restoreId in your database
                  }
                }
              });
            }
          });
      
      }// end of freshat initiallization for lite app
      else
      {
        document.addEventListener("deviceready",function(){


        window.Freshchat.init({

             appId                   : "12fdcb5b-dd2d-4d96-b5a1-a623e5c7633e",
             appKey                  : "e770aac6-9f93-42b6-9495-9904f1a2a3a4",
             gallerySelectionEnabled : true,
             cameraCaptureEnabled    : true,
             teamMemberInfoVisible   : true,
             config                  : { 
                                          headerProperty:
                                          {
                                            //Set Widget to be left to right.
                                            direction: 'ltr'
                                          }
                                      }
         }, function(success){
             console.log("This is called form the init callback");
         });

        //After initializing Freshchat in ios
        showSupportChat = function()
        {

          var userInfo = {
                         "name" : profile.first_name + ' ' + profile.last_name,
                         "email" : profile.email,
                         "externalId" : profile.username,
                         "countryCode" : "+91",
                         "phoneNumber" : profile.userprofile.phone_number
                      };

          Freshchat.updateUser(userInfo)
          window.Freshchat.showConversations();

        };
        document.getElementById("launch_conversations").onclick = showSupportChat;

         });

      } // end of initiallization for ios



      console.log('opened fresh chat');

} //end of Freshchat
`

**Comment by techaffinity** [comment]
Hi premjio  

We can access Freshchat SDK in mobile app only. 
Initially, call (window as any).Freshchat.init({ appId : "", appKey : "" }); });
Once it is successfuly initialized, you should make a call to showConversation or showFAQs.

**Comment by techaffinity** [comment]
Hi wishbooks 
Please refer #15  for the issue you mentioned. Thanks
