### ISSUE TITLE
Customizing ActionBar Title and Background color

### ISSUE THREAD

**Issue by alan-grixti** [techaffinity/freshchat-phonegap#12]
Hi,

I am trying to customize the text and background color of the conversation's ActionBar but this does not seem to be provided out of the box. Is there some workaround for it?

I suspect the plugin is using the original Freshchat SDK underneath, which that would mean that the guidelines [here](https://support.freshchat.com/support/solutions/articles/229492-freshchat-android-sdk-themes-and-customizations) can be used to customize the activity being instantiated.

Is it possible in some way to include the latter customizations into the phonegap plugin by using the `file-config` or `edit-config` tags in the `config.xml` file in order to propogate these settings?

**Comment by techaffinity** [comment]
Theme customisation is not yet implemented. it will come on feature release
