### ISSUE TITLE
IOS App Crash updateUser

### ISSUE THREAD

**Issue by sudheerrepala** [techaffinity/freshchat-phonegap#16]
IOS App Silently crashes when we use window.Freshchat.updateUser  or updateUserProperties.

**Comment by techaffinity** [comment]
Can you share me error log to identify this issue.

**Comment by sudheerrepala** [comment]
Hi Did you get a chance to look in to this?

**Comment by sudheerrepala** [comment]
Hi, turns out the phoneNumber should be a String in ios...   also i have forked the repo and made a little change in the ios file...

**Comment by mfouadegy** [comment]
same problem with me did you find solution ?
