### ISSUE TITLE
Cannot load NSManagedObjectModel.  nil is an illegal URL parameter

### ISSUE THREAD

**Issue by marceloaraujo** [techaffinity/freshchat-phonegap#18]
Hello.
I've been trying to use your plugin for Freshchat on an Ionic project but I got this error:
Cannot load NSManagedObjectModel.  nil is an illegal URL parameter

The Xcode shows an error on this line of the FreshchatPlugin.m file:
`[[Freshchat sharedInstance] initWithConfig:config];`

Is there anything else that I have to do after installing the plugin?
Thank you.

**Comment by jefsteward** [comment]
after you build ios, go to platforms/ios, then do: pod install

It seems you need to pod install everytime after you do ionic cordova build ios

**Comment by marceloaraujo** [comment]
@jefsteward Thanks for answering me. I tried your solution and it worked very well. 💯
