### ISSUE TITLE
Unable to export ios app because of freshchat

### ISSUE THREAD

**Issue by santosh-vishwakarma** [techaffinity/freshchat-phonegap#28]
This error I am getting when exporting the ionic app I have used fresh chat which working fine in android but not able to export ios

-c /Volumes/Data/palStuAppFreshbot/platforms/ios/PAL/Plugins/cordova-plugin-freshchat/FreshchatiOSPlugin/FreshchatPlugin.m -o /var/root/Library/Developer/Xcode/DerivedData/PAL-dlyudxdqxlqfvrcwclcqbvfgtrrv/Build/Intermediates/PAL.build/Debug-iphonesimulator/PAL.build/Objects-normal/x86_64/FreshchatPlugin.o
In file included from /Volumes/Data/palStuAppFreshbot/platforms/ios/PAL/Plugins/cordova-plugin-freshchat/FreshchatiOSPlugin/FreshchatPlugin.m:10:
/Volumes/Data/palStuAppFreshbot/platforms/ios/PAL/Plugins/cordova-plugin-freshchat/FreshchatiOSPlugin/FreshchatPlugin.h:9:9: fatal error: 'FreshchatSDK/FreshchatSDK.m' file not found
#import "FreshchatSDK/FreshchatSDK.m"
        ^
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC /var/root/Library/Developer/Xcode/DerivedData/PAL-dlyudxdqxlqfvrcwclcqbvfgtrrv/Build/Intermediates/PAL.build/Debug-iphonesimulator/PAL.build/Objects-normal/x86_64/FreshchatPlugin.o PAL/Plugins/cordova-plugin-freshchat/FreshchatiOSPlugin/FreshchatPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

Freshchat team, please let me know what I am doing wrong

**Comment by sianghung** [comment]
I am having the same issue, then I realised the FreshchatSDK folder was not copied over when we add the IOS platform, manually copying the folder over to the plugin folder introduce other errors.

Is still anyone maintaining this project???

**Comment by techaffinity** [comment]
We are looking into this and will keep you updated.

**Comment by techaffinity** [comment]
New update is available.Please install this plugin through the command line only and let us know if you still face this issue

**Comment by techaffinity** [comment]
New update is available for static SDK files and let us know if you still face this issue

**Comment by sianghung** [comment]
the issue comes back after I reinstall the plugin again
