### ISSUE TITLE
JSON format on Freshchat.updateUser(userInfo) is wrong on README.md

### ISSUE THREAD

**Issue by Lucaro-P** [techaffinity/freshchat-phonegap#3]
Hi @techaffinity. I'm using this plugin on my app and updating the user info through the Freshchat.updateUser(userInfo) function and it wasn't working when I implemented for the first time. So I contacted the FreshChat support and they told me that the right attributes are "firstName" and "lastName", not just "name". Can you fix this, please?

**Comment by techaffinity** [comment]
@Lucaro-P  We have updated README.md. Please check on the latest commit changes.

**Comment by Lucaro-P** [comment]
Thanks.
