### ISSUE TITLE
Integrating the Freshchat Phonegap plugin to our ionic3 mobile app.

### ISSUE THREAD

**Issue by koteshgit** [techaffinity/freshchat-phonegap#35]

**Comment by koteshgit** [comment]
We need an expert supprt to integrate the plugin from scratch.
It is urgent, as we need to integrate this asap.

**Comment by koteshgit** [comment]
Please let us know is it possible to provide support or not. So that we carry forward accordingly.

**Comment by techaffinity** [comment]
We already shared you all the details in the mail and we are closing this ticket.
