### ISSUE TITLE
Plugin failed on ios

### ISSUE THREAD

**Issue by jasonandress** [techaffinity/freshchat-phonegap#7]
I'm having an issue installing the plugin on ios. I've run the plugin add command with --verbose and have the below error.

Finding Podfile changes
  A FreshchatSDK

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `FreshchatSDK (~> 1.3.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `FreshchatSDK (~> 1.3.0)`.

----
Here's my cordova info
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    Cordova Platforms : ios 4.5.4
    Ionic Framework   : ionic1 1.3.5

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v6.11.2
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

**Comment by techaffinity** [comment]
Resolving dependencies of Podfile
[!] Unable to satisfy the following requirements:

FreshchatSDK (~> 1.3.0) required by Podfile

Confirm cocoaPod is installed in your mac , if installed please update the pod repos.
